### 회원가입
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "username",
  "password": "Password@1234",
  "email": "test@gmail.com",
  "introduction": "태스트 단어",
  "rolePassword": "67mE67CA67KI7Zi4",
  "nickname": "닉네임"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "Password@1234"
}

> {%
    client.log(response);
    const authorizationHeader = response.headers.valueOf('Authorization')
    client.global.set("access_token", authorizationHeader)
    client.log("Authorization header: " + authorizationHeader);
%}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json
Authorization: {{access_token}}

> {%
    const authToken = client.global.get("access_token");
    client.log("Request sent with authorization token: " + authToken);
%}



### 회원탈퇴
PUT localhost:8080/api/auth/signout
Content-Type: application/json
Authorization: {{access_token}}

{
  "password": "password@1234"
}